from django.urls import path

from main.views import (
    show_main, 
    show_experience, 
    create_experience,
    get_experience_json,
    delete_experience,
    show_education, 
    create_education,
    update_education,
    delete_education,
    get_education_json,
    show_skills, 
    create_skill, 
    update_skill, 
    delete_skill, 
    get_skill_json,
    show_achievements,
    create_achievement, 
    update_achievement, 
    delete_achievement, 
    get_achievement_json,
    show_certifications,
    create_certification, 
    update_certification, 
    delete_certification, 
    get_certification_json,
)

app_name = "main"

urlpatterns = [
    path("", show_main, name="show_main"),
    path("experience/", show_experience, name="show_experience"),
    path("experience/add/", create_experience, name="create_experience"),
    path("api/experience/", get_experience_json, name="get_experience_json"),
    path("experience/<uuid:experience_id>/delete/", delete_experience, name="delete_experience"),
    path("education/", show_education, name="show_education"),
    path("education/add/", create_education, name="create_education"),
    path("education/<uuid:education_id>/edit/", update_education, name="update_education"),
    path("education/<uuid:education_id>/delete/", delete_education, name="delete_education"),
    path("api/education/", get_education_json, name="get_education_json"),
    path("skills/", show_skills, name="show_skills"),
    path("skills/add/", create_skill, name="create_skill"),
    path("skills/<uuid:skill_id>/edit/", update_skill, name="update_skill"),
    path("skills/<uuid:skill_id>/delete/", delete_skill, name="delete_skill"),
    path("api/skills/", get_skill_json, name="get_skill_json"),
    path("achievements/", show_achievements, name="show_achievements"),
    path("achievements/add/", create_achievement, name="create_achievement"),
    path("achievements/<uuid:achievement_id>/edit/", update_achievement, name="update_achievement"),
    path("achievements/<uuid:achievement_id>/delete/", delete_achievement, name="delete_achievement"),
    path("api/achievements/", get_achievement_json, name="get_achievement_json"),
    path("certifications/", show_certifications, name="show_certifications"),
    path("certifications/add/", create_certification, name="create_certification"),
    path("certifications/<uuid:certification_id>/edit/", update_certification, name="update_certification"),
    path("certifications/<uuid:certification_id>/delete/", delete_certification, name="delete_certification"),
    path("api/certifications/", get_certification_json, name="get_certification_json"),
]