# Generated by Django 6.1.1 on 2026-09-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
