# Generated by Django 5.2.17 on 2026-09-14 14:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_education_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('soft', 'Soft Skill'), ('hard', 'Hard Skill')], default='soft', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('score', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('order', models.PositiveIntegerField(default=0, help_text='Urutan tampil, angka kecil duluan')),
            ],
            options={
                'ordering': ['category', 'order', '-score'],
            },
        ),
    ]
