# Generated by Django 5.2.17 on 2026-09-14 14:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('year', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('non_academic', 'Non Academic')], default='academic', max_length=20)),
                ('icon', models.CharField(default='🏆', max_length=10)),
                ('image', models.CharField(blank=True, help_text='Path gambar sertifikat untuk carousel', max_length=255, null=True)),
            ],
        ),
    ]
