# Generated by Django 5.2.17 on 2026-09-14 16:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_achievement_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('date_range', models.CharField(help_text='Contoh: July 2025 - July 2027', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='📜', max_length=10)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
